config/routes.rb
Rails.application.routes.draw do
  root to: "agents#random_agent"

  resources :agents do
    resources :uploaded_transactions
    resources :bulk_imports, only: [:new, :create]
  end
end

app/models/agent.rb
class Agent < ApplicationRecord
  has_many :uploaded_seller_transactions, class_name: "UploadedTransaction", foreign_key: :listing_agent_id
  has_many :uploaded_buyer_transactions, class_name: "UploadedTransaction", foreign_key: :selling_agent_id
  
  validates :first_name, :last_name, presence: true

  def all_transactions
    UploadedTransaction.where("listing_agent_id = ? OR selling_agent_id = ?", id, id)
  end

  def recent_transactions
    all_transactions.where("selling_date > ?", 6.months.ago)
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/uploaded_transaction.rb
require 'csv'

class UploadedTransaction < ApplicationRecord
  belongs_to :listing_agent, required: false, class_name: "Agent"
  belongs_to :selling_agent, required: false, class_name: "Agent"

  validates :address, :city, :state, :zip, :selling_date, :selling_price, presence: true
  validates :selling_price, :listing_price, numericality: { greater_than: 0, allow_nil: true }

  default_scope { order(selling_date: :desc) }
  scope :single_family_homes, -> { where(property_type: "single_family_home") }
  scope :sold, -> { where(status: "sold") }

  def self.csv_import(file, listing_agent_id)
    uploaded_transactions = []
    CSV.foreach(file.path, headers: true) do |row|
      uploaded_transactions << row.to_h.merge(listing_agent_id: listing_agent_id)
    end
    uploaded_transactions.uniq!{ |transaction| transaction.values_at("address", "zip", "selling_date") }
    UploadedTransaction.import(uploaded_transactions)
  end

  def full_address
    "#{address}, #{city}, #{state} #{zip}"
  end
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  include Pagy::Backend

  def show
    @agent = Agent.find(params[:id])
    @pagy, @uploaded_transactions = pagy(@agent.all_transactions)
  end

  def random_agent
    redirect_to agent_path(Agent.all.sample)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bulk_imports_controller.rb
class BulkImportsController < ApplicationController
	def create
    agent = Agent.find(params[:agent_id])
    UploadedTransaction.csv_import(params[:file], agent.id)
    redirect_to agent_path(agent), notice: "Records imported!"
  end

  private

  def uploaded_transaction_params
    params.require(:bulk_import).permit(:file, :agent_id)
  end
end

app/controllers/uploaded_transactions_controller.rb
class UploadedTransactionsController < ApplicationController
  before_action :find_agent
  
  def new
    @uploaded_transaction = @agent.uploaded_seller_transactions.new
  end

  def create
    @uploaded_transaction = @agent.uploaded_seller_transactions.create(uploaded_transaction_params)

    if @uploaded_transaction.save
      redirect_to agent_path(@agent), notice: "Transaction saved!"
    else
      render "new"
    end
  end

  private

  def find_agent
    @agent = Agent.find(params[:agent_id])
  end

  def uploaded_transaction_params
    params.require(:uploaded_transaction).permit(:address, :city, :state, :zip, :listing_agent, :listing_price, :listing_date, :selling_price, :selling_agent, :selling_date, :status, :property_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	include Pagy::Frontend
end

app/views/agents/show.html.slim
h1 = @agent.full_name
p = @agent.bio

= link_to "Add Transaction", new_agent_uploaded_transaction_path(@agent), class: "btn btn-primary mr-2"
= link_to "Bulk Import Transactions", new_agent_bulk_import_path(@agent), class: "btn btn-primary mx-2"

h3 Recent Transactions
table
  thead
    tr
      th Address
      th Listed
      th Listing Price
      th Sold
      th Selling Price
      th
  tbody
    - @uploaded_transactions.each do |uploaded_transaction|
      tr
        td = uploaded_transaction.full_address
        td = uploaded_transaction.listing_date
        td = uploaded_transaction.listing_price
        td = uploaded_transaction.selling_date
        td = uploaded_transaction.selling_price
div class="mt-2 d-flex justify-content-center"
  == pagy_bootstrap_nav(@pagy)

app/views/bulk_imports/new.html.slim
h1 Import Transactions

= form_tag agent_bulk_imports_path, multipart: true do
  .form-group
    = label_tag
    = file_field_tag 'file', class: "form-control"

  = submit_tag "Import", class: "btn btn-primary"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uploaded Transactions Manager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="<%= root_path %>">HomeSearch</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
             <li class="nav-item dropdown active">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Agents</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <% Agent.all.each do |agent| %>
                  <a class="dropdown-item" href="<%= agent_path(agent) %>"><%= agent.full_name %></a>
                <% end %>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/uploaded_transactions/new.html.slim
h1 New Transaction
- if @uploaded_transaction.errors.any?
  .error-explanation.alert.alert-danger
    .h4 #{ pluralize(@uploaded_transaction.errors.count, "error") } prohibited this transaction from being saved
    ul
      - @uploaded_transaction.errors.full_messages.each do |msg|
        li = msg

= form_for [@agent, @uploaded_transaction] do |f|
  .form-group
    = f.label :address
    = f.text_field :address, class: "form-control"
  .form-group
    = f.label :city
    = f.text_field :city, class: "form-control"
  .form-group
    = f.label :state
    = f.text_field :state, class: "form-control"
  .form-group
    = f.label :zip
    = f.text_field :zip, class: "form-control"
  .form-group
    = f.label :listing_date
    = f.text_field :listing_date, class: "form-control"
  .form-group
    = f.label :listing_price
    = f.text_field :listing_price, class: "form-control"
  .form-group
    = f.label :selling_date
    = f.text_field :selling_date, class: "form-control"
  .form-group
    = f.label :selling_price
    = f.text_field :selling_price, class: "form-control"
  .form-group
    = f.label :status
    = f.select :status, %w(sold pending closed cancelled expired active)
  .form-group
    = f.label :property_type
    = f.select :property_type, %w(condo single_family_home multi_family_home commercial mobile_home land)

  = f.submit "Save", class: "btn btn-primary"